default: &default
  adapter: postgresql
  encoding: unicode
  username: dee
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: airbnb_dev

production:
  <<: *default
  database: airbnb_prod